### ISSUE TITLE
[Task] folder structures

### ISSUE THREAD

**Issue by Jehadalmaliki** [Jehadalmaliki/Files-App-Back#1]
Folder Structure: Design the database schema to store folder structures efficiently. Implement recursive methods for fetching folder contents and managing nested folders.

creating folders, listing files/folders in a directory, deleting files/folders.

## TODO

- [ ] create folder  table
- [ ] create folder model
- [ ] create CRUD controllar
